name: turing
channels:
  - conda-forge
  - defaults
dependencies:
  # Core stack
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - pytorch-cpu
  - keras
  - pandas
  - scikit-learn
  - requests
  - pip
  - pip:
    - regional

  # Testing
  - pytest